{
 "title": "Devops Dashboard",
 "time": { "from": "now/w", "to": "now/w" },
 "panels": [
  {
   "title": "Cycle Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time in Days" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  cycle_time_value as value,\n  project as metric\nFROM cycle_time\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Lead Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time in Days" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  lead_time_value as value,\n  metric as metric\nFROM lead_time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "Deploy Frequency - KPI Portal",
   "type": "singlestat",
   "description": "Per Week",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  frequency as value,\n  project as metric\nFROM deployment_frequency\nWHERE project='KPI Portal'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Deploy Frequency - Farmer Hub",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  frequency as value,\n  project as metric\nFROM deployment_frequency\nWHERE project='Farmer Hub'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Deploy Frequency - DealerKart",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  frequency as value,\n  project as metric\nFROM deployment_frequency\nWHERE project='DealerKart'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Mean Time To Recovery",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  mttr_value as value,\n  project as metric\nFROM mttr\nORDER BY time ASC\n\n"
    }
   ]
  }
 ]
}