{
 "title": "MTTR DashBoard",
 "time": { "from": "now/w", "to": "now/w" },
 "panels": [
  {
   "title": "MTTR - KPI Portal",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  average_mttr_value as value,\n  project as metric\nFROM average_mttr\nWHERE project='KPI Portal'\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "MTTR - Farmer Portal",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  average_mttr_value as value,\n  project as metric\nFROM average_mttr\nWHERE project='Farmer Hub'\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "MTTR - DealerKart",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  average_mttr_value as value,\n  project as metric\nFROM average_mttr\nWHERE project='DealerKart'\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "MTTR Graph By Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  mttr_value as value,\n  project as metric\nFROM mttr\nORDER BY time ASC\n\n"
    }
   ]
  }
 ]
}